version: "3.9"

services:
  development_database:
    image: postgres
    restart: always
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_DB=boxeverything
      - POSTGRES_USER=boxeverything
      - POSTGRES_PASSWORD=boxeverything_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  development_minio:
    image: quay.io/minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    container_name: minio
    volumes:
      - ./data/minio/data:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio_box
    command: server /data --console-address ":9001"
